apiVersion: apps/v1
kind: Deployment
metadata:
  name: konoha-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konoha
  template:
    metadata:
      labels:
        app: konoha
    spec:
      containers:
      - name: konoha
        image: 599006410456.dkr.ecr.eu-central-1.amazonaws.com/uzumaki
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: konoha
    k8s-app: konoha
  name: konoha
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: asgbuggy
